backend:
  name: git-gateway
  branch: Mofix # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: brandnewguys/bng_shoptemplate-cms # Path to your GitHub repository
# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "../img/cms-upload" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "name",        name: "name",   widget: "string"}
      - {label: "title",       name: "title",  widget: "string"}
      - {label: "Layout",      name: "layout", widget: "hidden", default: "post"}
      - {label: "function",    name: "work",   widget: "string"}
      - {label: "number(1-3)", name: "num",    widget: "number"}
      - {label: "content",     name: "body",   widget: "markdown"}

